default: &default
   adapter: postgresql
   encoding: unicode
  
development:
   adapter: postgresql
   encoding: unicode
   database: lib_dev
   username: postgres
   password: ansh04032010$

test:
   adapter: postgresql
   encoding: unicode
   database: lib_test
   username: postgres
   password: ansh04032010$
 
production:
   adapter: postgresql
   encoding: unicode
   database: lib_prd
   username: rubyuser
   password: <Password for rubyuser>
